# Use an official Node runtime as a parent image
FROM node:14

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
RUN npm install

# Bundle app source
COPY . ./

# Start app
CMD ["npm", "run", "dev"]