version: '3'
services:
  api-gateway:
    build: ./api-gateway
    depends_on:
      - client
      - user-service
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8080:80"
  client:
    build:
      context: ./client
      #Prod: Dockerfile, Dev: Dockerfile.dev
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
  user-service:
    build:
      context: ./UserService
      #Prod: Dockerfile, Dev: Dockerfile.dev
      dockerfile: Dockerfile.dev
    depends_on:
      - user-db
    environment:
      - DATABASE_HOST=user-db
      - DATABASE_PORT=3306
      - FLASK_APP=app.app:create_app
    ports:
      - "5001:5000"
    volumes:
      - ./UserService/app:/app/app
  user-service-test:
    build:
      context: ./UserService
      #Prod: Dockerfile, Dev: Dockerfile.dev
      dockerfile: Dockerfile.dev
    command: pytest tests/
    environment:
      - "DATABASE_URI=sqlite:///:memory:"
    volumes:
      - ./UserService/tests:/app/tests
  user-db:
    build:
      context: ./user-db
      dockerfile: Dockerfile.dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - user-db-data:/var/lib/mysql
      - ./user-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./user-db/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=rootpassword"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  user-db-data:

