apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: stuartgavidia/businessapp:analyticsservicev1.14
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: DATABASE_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: MYSQL_DATABASE
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: analytics-service-config
                  key: FLASK_ENV
            - name: PLAID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secrets
                  key: PLAID_CLIENT_ID
            - name: PLAID_SECRET
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secrets
                  key: PLAID_SECRET
            - name: PLAID_ENV
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secrets
                  key: PLAID_ENV
            - name: PLAID_PRODUCTS
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secrets
                  key: PLAID_PRODUCTS
            - name: PLAID_COUNTRY_CODES
              valueFrom:
                secretKeyRef:
                  name: analytics-service-secrets
                  key: PLAID_COUNTRY_CODES
