apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
      - name: communication-service
        image: stuartgavidia/businessapp:communicationservicev1.1
        ports:
        - containerPort: 5103
