apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DATABASE_HOST: database-host.azure.com
  DATABASE_PORT: "3306"
  MYSQL_DATABASE: user_db
  CACHE_HOST: redis-host.azure.com
  CACHE_PORT: "6379"
  CACHE_DB: "0"
