name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  user-service-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build user-service-test for Testing
      run: |
        docker-compose -f docker-compose.yml build user-service-test
      
    - name: Run user-service-test for Testing
      run: |
        docker-compose -f docker-compose.yml run user-service-test

    - name: Cleanup Docker Service 1
      if: always()
      run: docker-compose -f docker-compose.yml down

  client-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build client-test for Testing
      run: |
        docker-compose -f docker-compose.yml build client-test
      
    - name: Run client-test for Testing
      run: |
        docker-compose -f docker-compose.yml run client-test

    - name: Cleanup Docker Service 2
      if: always()
      run: docker-compose -f docker-compose.yml down